services:
  client:
    build: ./client
    ports:
      - "3000:3000"
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      TEST_SERVICE_URL: "http://test-service:8000"
    secrets:
      - clerk_secret_key
    depends_on:
      - test-service
    stop_grace_period: 30s
  test-service:
    build: ./services/test-service
    ports:
      - "8001:8000"
secrets:
  clerk_secret_key:
    file: ./secrets/clerk_secret_key.txt