apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-judge

resources:
  - ../../base
  - ingress.yaml

images:
  - name: online-judge/gateway
    newTag: dev
  - name: online-judge/client
    newTag: dev
  - name: online-judge/user-service
    newTag: dev
  - name: online-judge/quiz-service
    newTag: dev
  - name: online-judge/attempt-service
    newTag: dev

patches:
  - path: allowed-origins.yaml

secretGenerator:
  - name: app-secrets
    files:
      - postgres_password=../../../secrets/postgres_password.txt
      - clerk_secret_key=../../../secrets/clerk_secret_key.txt
      - clerk_webhook_secret=../../../secrets/clerk_webhook_secret.txt
      - rabbitmq_password=../../../secrets/rabbitmq_password.txt
  - name: client-env
    envs:
      - ../../../client/.env.local
