apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  USER_SERVICE_URL: "http://user-service:8000"
  QUIZ_SERVICE_URL: "http://quiz-service:8000"
  ATTEMPT_SERVICE_URL: "http://attempt-service:8000"
  REDIS_URL: "redis://redis:6379/0"
  RATE_LIMIT_GLOBAL: "100"